#!/usr/bin/env bash
# PreToolUse guard: refuse hand-edits to files that scripts/project_os.py generates.
#
# AGENTS.md: "Do not edit these by hand." CI checks the drift, which means a hand-edit is
# discovered at the end of the work rather than at the moment it happens. This turns that into
# an immediate refusal with the correct instruction attached.
#
# Wire it up in .claude/settings.json:
#
#   { "hooks": { "PreToolUse": [ { "matcher": "Edit|Write|NotebookEdit",
#       "hooks": [ { "type": "command", "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/guard-generated-docs.sh" } ] } ] } }
#
# Exit 2 blocks the tool call and returns stderr to the agent.

set -euo pipefail

payload=$(cat)
path=$(printf '%s' "$payload" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)
[ -n "$path" ] || exit 0

case "$path" in
  */docs/DECISION_REGISTER.md|*/docs/ROADMAP.md|*/docs/BACKLOG.md|*/project/generated/*)
    cat >&2 <<'MSG'
Refused: this file is generated by scripts/project_os.py and must never be hand-edited.

Edit the source instead, then regenerate:
  project/decisions.json       -> docs/DECISION_REGISTER.md
  project/roadmap.json         -> docs/ROADMAP.md
  project/epics/*.json         -> docs/BACKLOG.md, project/generated/PROJECT_STATUS.md

  python3 scripts/project_os.py generate
  python3 scripts/project_os.py check
MSG
    exit 2
    ;;
  */docs/CLI.md)
    echo "Refused: docs/CLI.md is generated from the Python CLI. Run: python3 scripts/gen_docs.py" >&2
    exit 2
    ;;
esac
exit 0
