#!/usr/bin/env bash
# PreToolUse guard: refuse hand-edits to files that scripts/project_os.py generates.
#
# AGENTS.md: "Do not edit these by hand." CI checks the drift, which means a hand-edit is
# discovered at the end of the work rather than at the moment it happens. This turns that into
# an immediate refusal with the correct instruction attached.
#
# This is a convenience guard, not a safety boundary. Two limits are deliberate and must stay
# visible rather than be quietly assumed away:
#
#   * it sees only the structured file-writing tools the matcher names (Edit/Write/NotebookEdit).
#     A write performed through Bash - `sed -i`, a heredoc, `python3 -c "open(...,'w')"` - never
#     reaches this hook. Matching those would mean parsing shell, which a guard should not
#     attempt; `scripts/project_os.py check` and `scripts/gen_docs.py --check` remain the
#     authority and catch every path, including those.
#   * it fails OPEN. Any input it cannot interpret exits zero. A guard that can halt a session
#     on a malformed payload is worse than the mistake it prevents.
#
# Matching is done on the REAL path, made relative to the project directory and compared
# case-insensitively, because `docs/BACKLOG.md`, `docs/backlog.md`, `docs//BACKLOG.md` and
# `docs/adrs/../BACKLOG.md` are one file on an APFS volume. That is the same rule README.md
# states for protected provider names, and for the same reason: a barrier must not depend on
# how a name happens to be spelled.
#
# Wire it up in .claude/settings.json:
#
#   { "hooks": { "PreToolUse": [ { "matcher": "Edit|Write|NotebookEdit",
#       "hooks": [ { "type": "command", "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/guard-generated-docs.sh" } ] } ] } }
#
# Exit 2 blocks the tool call and returns stderr to the agent.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project="${CLAUDE_PROJECT_DIR:-$(cd "$here/../.." && pwd)}"

kind=$(PROJECT_DIR="$project" python3 -c '
import json, os, sys

GENERATED = {
    "docs/decision_register.md": "project_os",
    "docs/roadmap.md": "project_os",
    "docs/backlog.md": "project_os",
    "docs/cli.md": "gen_docs",
}
GENERATED_PREFIX = "project/generated/"

try:
    payload = json.load(sys.stdin)
    path = payload["tool_input"]["file_path"]
    if not isinstance(path, str) or not path:
        raise ValueError("no file path")
    project = os.environ["PROJECT_DIR"]
    real = os.path.realpath(os.path.join(project, path))
    relative = os.path.relpath(real, os.path.realpath(project)).replace(os.sep, "/").lower()
    if relative.startswith("../"):
        raise ValueError("outside the project")
    if relative.startswith(GENERATED_PREFIX):
        print("project_os")
    else:
        print(GENERATED.get(relative, ""))
except Exception:
    pass
' 2>/dev/null <<<"$(cat)" || true)

case "$kind" in
  project_os)
    cat >&2 <<'MSG'
Refused: this file is generated by scripts/project_os.py and must never be hand-edited.

Edit the source instead, then regenerate:
  project/decisions.json       -> docs/DECISION_REGISTER.md
  project/roadmap.json         -> docs/ROADMAP.md
  project/epics/*.json         -> docs/BACKLOG.md, project/generated/PROJECT_STATUS.md

  python3 scripts/project_os.py generate
  python3 scripts/project_os.py check
MSG
    exit 2
    ;;
  gen_docs)
    echo "Refused: docs/CLI.md is generated from the Python CLI. Run: python3 scripts/gen_docs.py" >&2
    exit 2
    ;;
esac
exit 0
