//! Regenerates the golden JSON fixtures in `tests/golden/` (E02-S03).
//!
//! Mirrors `scripts/characterize.py generate` on the Python side: golden files are
//! regenerated by running code, never hand-edited, so they can never silently drift from
//! what `Diagnostic`/`serde` actually produce. Run from this crate's directory after an
//! intentional, reviewed change to `Diagnostic`'s shape:
//!
//! ```sh
//! cargo run --example print_golden
//! ```
//!
//! Review the resulting diff before committing - this tool does not know whether a change is
//! correct, only how to reproduce it.

use cancellai_model::{Diagnostic, ErrorCategory};

const CASES: [(ErrorCategory, &str, &str); 6] = [
    (
        ErrorCategory::InvalidInput,
        "requested provider root escapes the operator's home directory; refusing",
        "invalid_input.json",
    ),
    (
        ErrorCategory::SafetyBlock,
        "candidate is covered by a protected name; the barrier refused it",
        "safety_block.json",
    ),
    (
        ErrorCategory::IncompleteInventory,
        "scan was partial; destructive authority is withheld for this scope",
        "incomplete_inventory.json",
    ),
    (
        ErrorCategory::CompatibilityFailure,
        "provider layout is unrecognized by this build",
        "compatibility_failure.json",
    ),
    (
        ErrorCategory::MutationFailure,
        "revalidation found the plan stale; the action was safely skipped",
        "mutation_failure.json",
    ),
    (
        ErrorCategory::InternalFault,
        "unexpected internal error",
        "internal_fault.json",
    ),
];

fn main() {
    let golden_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden");
    for (category, message, file) in CASES {
        let diagnostic = Diagnostic::new(category, message);
        let json = serde_json::to_string_pretty(&diagnostic).expect("serializable");
        let path = golden_dir.join(file);
        std::fs::write(&path, format!("{json}\n"))
            .unwrap_or_else(|e| panic!("writing {path:?}: {e}"));
        println!("wrote {}", path.display());
    }
}
