#!/usr/bin/env python3
"""Generate and validate docs/PLATFORMS.md's platform capability matrix (E20-S03).

`project/platforms.json` is the source of truth. `generate` renders it into
docs/PLATFORMS.md; `check` verifies that rendering is current (like
project_os.py's own generated-docs drift check) and, more importantly, cross-
validates every platform's claim against real evidence this script can find in
the repository rather than trusting the JSON on its own word:

- a platform claiming CI coverage (`ci_check_job`/`ci_quality_job`) must have
  every one of its `ci_os_labels` actually present in the corresponding job's
  `os:` matrix in .github/workflows/rust.yml (parsed with a small regex, like
  scripts/check_workflows.py already does elsewhere in this repository - no
  YAML dependency, matching this project's stdlib-only tooling convention);
- every `evidence_tests` entry must be the name of a `#[test]` function this
  script can actually find defined somewhere under rust/crates/ - a claim
  cannot be backed by prose alone;
- `tier: 1` requires CI on both jobs and both `identity`/`mutation`
  capabilities verified - a platform cannot be declared tier 1 by editing the
  `tier` field in isolation.

This is what this story's acceptance criteria ("no platform is called
supported without required CI and destructive safety fixtures") and
verification contract ("generated platform matrix check") mean in practice.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
PLATFORMS_JSON = ROOT / "project" / "platforms.json"
PLATFORMS_MD = ROOT / "docs" / "PLATFORMS.md"
RUST_WORKFLOW = ROOT / ".github" / "workflows" / "rust.yml"
RUST_CRATES = ROOT / "rust" / "crates"

VALID_CAPABILITY_STATES = {"verified", "unverified", "unsupported"}
JOB_HEADER_RE = re.compile(r"^  ([A-Za-z][\w-]*):\s*$", re.MULTILINE)
OS_MATRIX_RE = re.compile(r"^\s*os:\s*\[([^\]]*)\]\s*$", re.MULTILINE)
TEST_FN_RE = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")


class PlatformsError(RuntimeError):
    pass


def load_platforms() -> dict[str, Any]:
    try:
        data = json.loads(PLATFORMS_JSON.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise PlatformsError(f"missing {PLATFORMS_JSON.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise PlatformsError(f"{PLATFORMS_JSON.relative_to(ROOT)}: invalid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise PlatformsError(f"expected a JSON object in {PLATFORMS_JSON.relative_to(ROOT)}")
    return data


def job_os_labels(workflow_text: str, job_name: str) -> set[str] | None:
    """The `os:` matrix labels for one job block, or None if the job/matrix is absent.

    Splits the workflow on top-level (2-space-indented) job headers rather than trying to
    parse YAML generally - the same "check repository-owned policy from source text" approach
    scripts/check_workflows.py already uses, deliberately avoiding a YAML dependency.
    """
    headers = list(JOB_HEADER_RE.finditer(workflow_text))
    for i, m in enumerate(headers):
        if m.group(1) != job_name:
            continue
        start = m.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(workflow_text)
        block = workflow_text[start:end]
        os_match = OS_MATRIX_RE.search(block)
        if not os_match:
            return None
        return {label.strip() for label in os_match.group(1).split(",") if label.strip()}
    return None


def find_test_function_names() -> set[str]:
    """Every `fn` name that appears anywhere under rust/crates/ - a coarse but real check.

    Deliberately does not require the function to carry `#[test]` immediately above it (that
    would need real parsing of attribute lines, fragile against this codebase's own multi-line
    doc-comment-heavy style) - a name collision with a non-test function of the same name is a
    false negative this script would miss, not a false positive that could wrongly pass a
    platform's claim, so this stays on the conservative side of "cannot verify" rather than
    "confidently wrong."
    """
    names: set[str] = set()
    for path in RUST_CRATES.rglob("*.rs"):
        text = path.read_text(encoding="utf-8", errors="replace")
        names.update(TEST_FN_RE.findall(text))
    return names


def platform_markdown(data: dict[str, Any]) -> str:
    lines = [
        "# Platform Support Model",
        "",
        "<!-- Generated by scripts/check_platforms.py from project/platforms.json. Do not edit by hand. -->",
        "",
        (
            "This is the target-engine (Rust) platform capability matrix - what this repository's "
            "own CI and test suite actually verify today, not an aspiration. `tier: 1` means real, "
            "CI-verified identity **and** mutation (deletion) capability; `tier: 2` means the "
            "platform is a named target but has not yet met that bar for at least one capability. "
            "See `docs/architecture/PLATFORM_MODEL.md` for the underlying capability seams "
            "(`IdentityObserver`, `MutationExecutor`, ...) each row's `identity`/`mutation` column "
            "refers to."
        ),
        "",
        "| Platform | Tier | CI (check) | CI (quality) | Identity | Mutation |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for p in data["platforms"]:
        caps = p["capabilities"]
        lines.append(
            f"| {p['title']} | {p['tier']} | "
            f"{'yes' if p['ci_check_job'] else 'no'} | {'yes' if p['ci_quality_job'] else 'no'} | "
            f"{caps['identity']} | {caps['mutation']} |"
        )
    lines.append("")
    for p in data["platforms"]:
        lines.append(f"## {p['title']}")
        lines.append("")
        lines.append(p["notes"])
        lines.append("")
        if p["evidence_tests"]:
            lines.append("Evidence (real test functions in `rust/crates/`):")
            lines.append("")
            lines.extend(f"- `{name}`" for name in p["evidence_tests"])
        else:
            lines.append("Evidence: none yet - disclosed, not silently assumed from another platform.")
        lines.append("")
    lines.extend(
        [
            "## Tier 2, further out",
            "",
            "- SSH remote hosts.",
            "- Dev Containers.",
            "- Ephemeral CI runners.",
            "- Codespaces-like developer environments.",
            "",
            "None of these are named platforms above because none has begun implementation; they "
            "are recorded here as acknowledged future scope, not as a claim about current behavior.",
            "",
            "## Unsupported consumer platforms",
            "",
            "Mobile operating systems are not a product target. cancellAI governs development machines and development execution environments.",
            "",
            "## What a non-tier-1 platform does today",
            "",
            (
                "Unsupported/tier-2 mutation capability never means an unverified guess at "
                "deletion. `cancellai-platform`'s observers (`IdentityObserver`, "
                "`AllocationObserver`, ...) report a distinct `Unsupported` fact rather than a "
                "possibly-wrong result, and the safety kernel (`cancellai-safety::root_capability`, "
                "`cancellai-safety::mutation_executor`) fails closed on it (SI-002, SI-017) - "
                "inspection/planning commands remain available, but `clean` cannot proceed to a "
                "real deletion. This is explicit refusal, not silent partial behavior "
                "(`docs/architecture/PLATFORM_MODEL.md`)."
            ),
            "",
            "## Cross-platform rule",
            "",
            "The domain layer does not expose Unix-only identity assumptions. Platform "
            "implementations must provide capability-aware abstractions for:",
            "",
            "- filesystem object identity;",
            "- volume/filesystem boundary;",
            "- symbolic links, junctions, mount points, and reparse points;",
            "- allocated/reclaimable size estimation;",
            "- process/activity observation;",
            "- atomic rename/move guarantees;",
            "- user-service runtime;",
            "- notifications;",
            "- path normalization and case behavior.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def validate(data: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    workflow_text = RUST_WORKFLOW.read_text(encoding="utf-8") if RUST_WORKFLOW.exists() else ""
    check_labels = job_os_labels(workflow_text, "check") or set()
    quality_labels = job_os_labels(workflow_text, "quality") or set()
    test_names = find_test_function_names()

    seen_ids: set[str] = set()
    for p in data.get("platforms", []):
        where = p.get("id", "<unknown>")
        if where in seen_ids:
            errors.append(f"{where}: duplicate platform id")
        seen_ids.add(where)

        caps = p.get("capabilities", {})
        for cap_name in ("identity", "mutation"):
            state = caps.get(cap_name)
            if state not in VALID_CAPABILITY_STATES:
                errors.append(f"{where}: capabilities.{cap_name} must be one of {sorted(VALID_CAPABILITY_STATES)}, got {state!r}")

        if p.get("ci_check_job"):
            missing = set(p.get("ci_os_labels", [])) - check_labels
            if missing:
                errors.append(
                    f"{where}: ci_check_job is true but {sorted(missing)} not found in rust.yml's 'check' job os matrix {sorted(check_labels)}"
                )
        if p.get("ci_quality_job"):
            missing = set(p.get("ci_os_labels", [])) - quality_labels
            if missing:
                errors.append(
                    f"{where}: ci_quality_job is true but {sorted(missing)} not found in "
                    f"rust.yml's 'quality' job os matrix {sorted(quality_labels)}"
                )

        for test_name in p.get("evidence_tests", []):
            if test_name not in test_names:
                errors.append(f"{where}: evidence_tests references {test_name!r}, which is not the name of any fn found under rust/crates/")

        if p.get("tier") == 1:
            required = (
                p.get("ci_check_job") is True
                and p.get("ci_quality_job") is True
                and caps.get("identity") == "verified"
                and caps.get("mutation") == "verified"
            )
            if not required:
                errors.append(
                    f"{where}: declared tier 1 but does not meet the tier-1 bar (ci_check_job, "
                    "ci_quality_job, and both capabilities must be 'verified') - this is exactly "
                    "the claim this story's AC1 exists to prevent"
                )

    return errors


def cmd_generate() -> int:
    data = load_platforms()
    errors = validate(data)
    if errors:
        print("PLATFORMS ERROR:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 2
    PLATFORMS_MD.write_text(platform_markdown(data), encoding="utf-8")
    print(f"wrote {PLATFORMS_MD.relative_to(ROOT)}")
    return 0


def cmd_check() -> int:
    try:
        data = load_platforms()
    except PlatformsError as exc:
        print(f"PLATFORMS ERROR: {exc}", file=sys.stderr)
        return 2
    errors = validate(data)
    rendered = platform_markdown(data)
    current = PLATFORMS_MD.read_text(encoding="utf-8") if PLATFORMS_MD.exists() else ""
    if current != rendered:
        errors.append(
            f"{PLATFORMS_MD.relative_to(ROOT)} does not match project/platforms.json; run `python3 scripts/check_platforms.py generate`"
        )
    if errors:
        print("PLATFORMS ERROR:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 2
    print(f"platforms OK: {len(data['platforms'])} platforms, generated matrix current, all CI/evidence claims verified")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate and validate docs/PLATFORMS.md's platform capability matrix.")
    parser.add_argument("command", nargs="?", default="check", choices=["check", "generate"])
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "generate":
        return cmd_generate()
    return cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
