#!/usr/bin/env python3
"""Regenerate docs/CLI.md from cancellai's own argparse definitions.

This keeps the CLI reference honest: it is rendered straight from
`cancellai.build_parser()`, the same object that produces `--help`, so the
docs cannot silently drift from the real flags.

Usage:
    python3 scripts/gen_docs.py           # regenerate docs/CLI.md
    python3 scripts/gen_docs.py --check   # exit 1 if docs/CLI.md is stale

Run in `--check` mode by CI (see .github/workflows/tests.yml) and by
`.pre-commit-config.yaml` so a flag change can never ship without a matching
doc update.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Fixed width so the generated help text is identical regardless of the
# terminal/CI runner this script happens to run in.
os.environ["COLUMNS"] = "100"

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import cancellai  # noqa: E402  (must follow the sys.path tweak above)

OUTPUT = REPO_ROOT / "docs" / "CLI.md"

HEADER = """# CLI reference

<!-- Auto-generated by scripts/gen_docs.py from cancellai's argparse definitions. Do not edit by hand. -->
"""


def render() -> str:
    parser = cancellai.build_parser()
    lines = [HEADER, "## `cancellai`", "", "```text", parser.format_help().rstrip(), "```", ""]

    subparsers_action = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    for name, subparser in subparsers_action.choices.items():
        lines += [f"## `cancellai {name}`", "", "```text", subparser.format_help().rstrip(), "```", ""]

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("docs/CLI.md is out of date. Run `python3 scripts/gen_docs.py` and commit the result.", file=sys.stderr)
            return 1
        print("docs/CLI.md is up to date.")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
